### ISSUE TITLE
Refactor rdiffnet

### ISSUE THREAD

**Issue by gvegayon** [USCCANA/netdiffuseR#45]
Example of flowchart using [mermaid](https://mermaid.live/edit#pako:eNpVjr2OwkAMhF_FcsVJ5AVSIB3JQYMEEnRZCitxsivYHzkbIZTk3W9DmjtX9sw3I49Y-4Yxx_bpX7UmiXArlYM031WhxfTRUn-HLNtNR45gveP3BPvN0UOvfQjGdV8rv18gKMbTgjFEbdxjXq3ikz87nqCsThSiD_e_zu3lJ_ipzEWn-v-OFk6pQ9VS3lJWk0BB8kFwi5bFkmnS--OiKIyaLSvM09qQPBQqNyeOhuivb1djHmXgLYofOo2p8NmnawgNRS4NdUJ2ReZfufpaQg) (You don't need to use this, draw.io also has this)

```mermaid
flowchart LR
  is_seedpnodes_list{Is seed p nodes list} -->|Yes| B
  is_seedpnodes_list -->|No| C
```

The ideal function should have:

- Allow passing a list for some of the arguments, in which case it assumes a multi-behavior model.
- Arguments are are not passed as list, should be recycled, e.g., if `seed.p.nodes` is a list but `seed.nodes` as a vector (indicating seed vertices), then the program should do something like `seed.nodes <- list(seed.nodes, seed.nodes)`

Need to think about the sim process.

For the preprocessing, you could have something like this:

```r
rdiffnet_validate_args <- function(seed.p.nodes, seed.nodes, behavior) {
   ... do all the checks to validate length and stuff ...
   list(
     seed.p.nodes = ...,
     seed.nodes = ...,
     behavior = ...,
     num_of_behaviors = ...
   )
}

rdiffnet <- function( ... ) {
  
    validated_args <- rdiffnet_validate_args(seed.p.nodes, seed.nodes, behavior)

    ....

    # if you want to use seed.p.nodes
    validated_args$seed.p.nodes
}
```

**Comment by gvegayon** [comment]
```r

n <- 20
thr <- .3
thr <- rep(.3, n)

thr <- function(x) runif(n)

thr_final <- if (length(thr) == 1) function() rep(thr, n)
else if (length(thr) == n) function() thr
else if (is.function(thr)) function() thr()

# IN the simulation, replace
# thr < exposure
# with
# thr() < exposure
# So, this handles all the cases.
```

**Comment by aoliveram** [comment]
Hi @gvegayon! LMK what do you think.

**Comment by gvegayon** [comment]
Adding a reference to the equations: https://github.com/USCCANA/netdiffuseR/pull/46#issuecomment-2471849855
