### ISSUE TITLE
netdiffuseR tutorial

### ISSUE THREAD

**Issue by map42** [USCCANA/netdiffuseR#6]
Is there any web tutorial of the package or video of the workshop you did on netdiffuseR?

Thank you,
Avi

**Comment by gvegayon** [comment]
Hey,

We do have a video of the workshop which we will update soon. For now you can take a look at the package's vignettes (https://cran.r-project.org/web/packages/netdiffuseR/ there's a lot of material there)

Best,

**Comment by map42** [comment]
Hi,

Thank you so much for this

It is great to know the video will be available soon, we will be thrilled to watch it when it comes out
The work you did is outstanding.

How can we be updated about its release ?

**Comment by map42** [comment]
Hi,

Thank you so much for this

It is great to know the video will be available soon, we will be thrilled to watch it when it comes out
The work you did is outstanding.

How can we be updated about its release ?

**Comment by gvegayon** [comment]
Hi there,

Is now online on [youtube](https://www.youtube.com/playlist?list=PLT-GgRN1lFI4coHDqkRJm3flDw9e1gg2P), and the workshop materials can be found [here](https://github.com/USCCANA/netdiffuseR/tree/master/doc/conferences/20160400_sunbelt2016/).

Best,

**Comment by map42** [comment]
Thank you!

This is a fantastic help.

Will it be possible to link the presentation itself as the slides are not very clear in the video?

Thank you so much for the help, it is highly appreciated!

**Comment by gvegayon** [comment]
All the workshop material, including slides and sorce code is [here](https://github.com/USCCANA/netdiffuseR/tree/master/doc/conferences/20160400_sunbelt2016/).

**Comment by Fabrizio-Marini** [comment]
Hello, I've noticed that the link with the workshop material is offline, is it possible to obtain the material in another way?

**Comment by gvegayon** [comment]
Hey, yes, they are now [here](https://github.com/USCCANA/netdiffuseR/tree/master/tutorials/sunbelt2016

**Comment by Fabrizio-Marini** [comment]
Thank you very much.
